root: true
env: {
  browser: true,
  node: true,
  es2022: true,
}
extends:
  - eslint:recommended
  - plugin:vue/recommended
  - plugin:nuxt/recommended
  - prettier
rules:
  'vue/multi-word-component-names': 'off'